title: Kanan Gandhi
description: Penetration Tester Portfolio
theme: jekyll-theme-hacker

markdown: kramdown

collections:
  cases:
    output: true

header_pages:
  - index.md
  - about.md
  - contact.md
