title: Kanan Gandhi
description: Web Application Security & QA Consultant Portfolio
markdown: kramdown

include:
  - cases
  - .nojekyll

collections:
  cases:
    output: true

header_pages:
  - index.html
  - about.md
  - contact.md

plugins:
  - jekyll-feed
